###############################################################################
# Copyright (c) 2021, 2024 Eclipse contributors
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Matthias Mail√§nder - initial setup
###############################################################################

name: Continuous Integration
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ChemClipse
      uses: actions/checkout@v3

    - uses: sdkman/sdkman-action@main
      name: Setup Temurin
      id: temurin
      with:
        candidate: java
        version: 17.0.11-tem

    - uses: sdkman/sdkman-action@main
      name: Setup Maven
      id: maven
      with:
        candidate: maven
        version: 3.9.6

    - name: Build with Maven
      run: |
        source $HOME/.sdkman/bin/sdkman-init.sh
        mvn -f chemclipse/releng/org.eclipse.chemclipse.aggregator/pom.xml -T 1C verify -Pci --batch-mode --no-transfer-progress
